# Generated by Django 4.1 on 2025-04-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_variant_name', models.CharField(max_length=200)),
                ('product_sp', models.FloatField(max_length=10)),
                ('product_mrp', models.FloatField(max_length=10)),
                ('product_discount', models.FloatField(max_length=10)),
                ('product_size', models.CharField(max_length=20)),
                ('product_description', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_color', models.CharField(max_length=200)),
                ('product_availability', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_img_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_img', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetail', to='ecommerce.productdetail')),
            ],
        ),
    ]
