# Generated by Django 4.1 on 2025-04-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_productdetail_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='forgot_password_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
