# Generated by Django 4.1 on 2025-04-23 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_customer_forgot_password_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_img_name', models.CharField(default='', max_length=200)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_size', models.CharField(max_length=20)),
                ('product_color', models.CharField(max_length=20)),
                ('product_price', models.FloatField(max_length=10)),
                ('product_total_price', models.FloatField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='ecommerce.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetails', to='ecommerce.productdetail')),
                ('product_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimage', to='ecommerce.productimage')),
            ],
        ),
    ]
