# Generated by Django 4.1 on 2025-04-30 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_addtocart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_price', models.FloatField(max_length=10)),
                ('product_size', models.CharField(max_length=20)),
                ('product_description', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_image', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerorder', to='ecommerce.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetailsorder', to='ecommerce.productdetail')),
                ('product_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimageorder', to='ecommerce.productimage')),
            ],
        ),
    ]
