# Generated by Django 4.1 on 2025-06-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='product_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='product_total_price',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='addtocart',
            unique_together={('customer', 'product', 'product_size', 'product_color')},
        ),
    ]
