# Generated by Django 4.1 on 2025-06-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_remove_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='productdetail', to='ecommerce.productdetail'),
        ),
    ]
