# Generated by Django 4.1 on 2025-06-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addtocart',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='product_price',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='product_total_price',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetail', to='ecommerce.productdetail'),
        ),
    ]
