# Generated by Django 4.1 on 2025-06-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_addtocart_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='product_total_price',
            field=models.FloatField(default=1, max_length=10),
        ),
    ]
