# Generated by Django 4.1 on 2025-06-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_customer_gender_order_product_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='product_img_name',
        ),
    ]
