# Generated by Django 4.1 on 2025-06-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_addtocart_product_img_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='product_img_name',
        ),
    ]
