# Generated by Django 4.1 on 2025-06-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_remove_addtocart_product_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='product_img_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
